"""empty message

Revision ID: 011a63e0d7ff
Revises: 43c167872381
Create Date: 2022-12-28 15:03:29.655173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011a63e0d7ff'
down_revision = '43c167872381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
